export const textos = {
  pt: {
    nav: {
      oHostel: 'O Hostel',
      acomodacoes: 'Acomodações',
      comodidades: 'Comodidades',
      vibe: 'A vibe',
      regiao: 'A região',
      depoimentos: 'Depoimentos',
      localizacao: 'Localização',
      abrirMenu: 'Abrir menu',
      fecharMenu: 'Fechar menu',
    },
    footer: {
      faleConosco: 'Fale conosco',
      sigaAGente: 'Siga a gente',
    },
    botaoWhatsApp: {
      rotuloPadrao: 'Reserve pelo WhatsApp',
      mensagem: (nome: string) =>
        `Ola! Vi o site do ${nome} e quero saber valores e disponibilidade.`,
    },
    pagina: {
      acomodacoesEyebrow: 'Acomodações',
      acomodacoesTitulo: 'Escolha seu canto',
      acomodacoesCta: 'Consultar disponibilidade no WhatsApp',
      casaTitulo: 'A casa',
      comodidadesEyebrow: 'Comodidades',
      comodidadesTitulo: 'A vida por aqui',
      vibeEyebrow: 'A vibe',
      vibeTitulo: 'Como é ficar aqui',
      regiaoEyebrow: 'A região',
      regiaoTitulo: 'Explore os arredores',
      comoChegarTitulo: 'Como chegar',
      depoimentosEyebrow: 'Depoimentos',
      depoimentosTitulo: 'Quem passou por aqui',
      depoimentoTraduzido: 'Traduzido do português.',
      localizacaoEyebrow: 'Localização',
      localizacaoTitulo: 'Onde estamos',
      fotoCredito: 'Foto:',
      ctaFinalTitulo: 'Reserve direto com a gente',
      ctaFinalTexto: 'Chame no WhatsApp e combine sua estadia direto com quem cuida da casa.',
    },
    mapa: {
      titulo: 'Mapa',
    },
  },
  en: {
    nav: {
      oHostel: 'The Hostel',
      acomodacoes: 'Rooms',
      comodidades: 'Amenities',
      vibe: 'The vibe',
      regiao: 'The area',
      depoimentos: 'Reviews',
      localizacao: 'Location',
      abrirMenu: 'Open menu',
      fecharMenu: 'Close menu',
    },
    footer: {
      faleConosco: 'Get in touch',
      sigaAGente: 'Follow us',
    },
    botaoWhatsApp: {
      rotuloPadrao: 'Book on WhatsApp',
      mensagem: (nome: string) =>
        `Hi! I saw ${nome}'s website and I'd like to know prices and availability.`,
    },
    pagina: {
      acomodacoesEyebrow: 'Rooms',
      acomodacoesTitulo: 'Pick your corner',
      acomodacoesCta: 'Check availability on WhatsApp',
      casaTitulo: 'The house',
      comodidadesEyebrow: 'Amenities',
      comodidadesTitulo: 'Life around here',
      vibeEyebrow: 'The vibe',
      vibeTitulo: 'What it feels like here',
      regiaoEyebrow: 'The area',
      regiaoTitulo: 'Explore the surroundings',
      comoChegarTitulo: 'Getting here',
      depoimentosEyebrow: 'Reviews',
      depoimentosTitulo: 'Who has stayed here',
      depoimentoTraduzido: 'Translated from Portuguese.',
      localizacaoEyebrow: 'Location',
      localizacaoTitulo: 'Where we are',
      fotoCredito: 'Photo:',
      ctaFinalTitulo: 'Book directly with us',
      ctaFinalTexto:
        "Message us on WhatsApp and arrange your stay directly with the people who run the house.",
    },
    mapa: {
      titulo: 'Map',
    },
  },
  es: {
    nav: {
      oHostel: 'El Hostel',
      acomodacoes: 'Habitaciones',
      comodidades: 'Comodidades',
      vibe: 'El ambiente',
      regiao: 'La zona',
      depoimentos: 'Reseñas',
      localizacao: 'Ubicación',
      abrirMenu: 'Abrir menú',
      fecharMenu: 'Cerrar menú',
    },
    footer: {
      faleConosco: 'Contáctanos',
      sigaAGente: 'Síguenos',
    },
    botaoWhatsApp: {
      rotuloPadrao: 'Reserva por WhatsApp',
      mensagem: (nome: string) =>
        `¡Hola! Vi el sitio web de ${nome} y me gustaría saber precios y disponibilidad.`,
    },
    pagina: {
      acomodacoesEyebrow: 'Habitaciones',
      acomodacoesTitulo: 'Elige tu rincón',
      acomodacoesCta: 'Consultar disponibilidad por WhatsApp',
      casaTitulo: 'La casa',
      comodidadesEyebrow: 'Comodidades',
      comodidadesTitulo: 'La vida por aquí',
      vibeEyebrow: 'El ambiente',
      vibeTitulo: 'Cómo es estar aquí',
      regiaoEyebrow: 'La zona',
      regiaoTitulo: 'Explora los alrededores',
      comoChegarTitulo: 'Cómo llegar',
      depoimentosEyebrow: 'Reseñas',
      depoimentosTitulo: 'Quién ha pasado por aquí',
      depoimentoTraduzido: 'Traducido del portugués.',
      localizacaoEyebrow: 'Ubicación',
      localizacaoTitulo: 'Dónde estamos',
      fotoCredito: 'Foto:',
      ctaFinalTitulo: 'Reserva directo con nosotros',
      ctaFinalTexto:
        'Escríbenos por WhatsApp y organiza tu estadía directo con quienes cuidan la casa.',
    },
    mapa: {
      titulo: 'Mapa',
    },
  },
} as const;
